### ISSUE TITLE
Not working 4.7.2 

### ISSUE THREAD

**Issue by pa-philos** [Lewiscowles1986/WordPressSVGPlugin#11]
Shows general error of "This type of file is not allowed due to security measures".

All I did was clone the repo and put the folder into wp-content/plugins.

**Comment by Lewiscowles1986** [comment]
Sorry, just tested it is working for me. You have to activate the plugin as well as clone repo and put into plugins (as with all WP plugins); not sure if that was done (wasn't mentioned). I'll screen record the test-site I used to quick-check online.

**Comment by Lewiscowles1986** [comment]
Right I've just managed to replicate the problem... Looking for a workaround

**Comment by Lewiscowles1986** [comment]
Fixed in 1.6.4 release
