### ISSUE TITLE
Limit CSS Scope?

### ISSUE THREAD

**Issue by dmhendricks** [Lewiscowles1986/WordPressSVGPlugin#24]
Some plugins/themes are irresponsible in WP Admin and do not give proper SVG dimensions (else they are overridden by `!important`). Example where the menu SVG icon is huge:

![Huge SVG menu icon example](https://i.snag.gy/OC4T67.jpg "Huge SVG menu icon example")

This particular example **has been fixed** in the latest WPB Page Builder, however, I had noticed it in other themes/plugins that use SVG. It's been awhile, but I remember it being a huge deal with the [Jupiter](https://themeforest.net/item/jupiter-multipurpose-responsive-theme/5177775) theme... Several of the theme's SVGs were massive.

- Can we limit the scope of the `width: 100% !important; height: auto !important;` CSS in the admin, perhaps at least to #wpbody? This wouldn't fix the Jupiter issue, but it would fix all menu icon issues. I'm not sure how to limit it further because you want SVGs to display for any custom field (such as ACF, Carbon Fields, etc) that might be used...
- Do we need `!important`? Else, perhaps injecting as external CSS with a high priority in the page head so that other `!important` CSS can override it?

I can install Jupiter in a local VM and try it to see if I can reproduce a situation that can be looked at, but I will have to wait until I have time. It may have been fixed in the latest release - I just mentioned that one because I remembering it being a "huge" deal. If it is broken, I can send you appropriate testing materials, if desired.

**Comment by Lewiscowles1986** [comment]
There was a commit for SVG sizing. I'd be interested in seeing if this is still active in recent (is the screenshot above from a 1.8.1?)

**Comment by dmhendricks** [comment]
No, I was using 1.8.0, and I actually just faked the screenshot by modding the CSS to show you what it _used_ to look like before WPBakery updated. I will try to see if I can find an actually issue with the latest and without manipulating CSS.

**Comment by Lewiscowles1986** [comment]
This is now fixed. Sorry it took a while 👍
